# Dependencies
markdown:         kramdown
highlighter:      rouge
gems: ["jekyll-paginate"]

# Permalinks
permalink:        pretty

# Setup
title:            TryAlgo
avatar:           /public/apple-touch-icon-144-precomposed.png
tagline:          'Un livre de programmation'
description:      'Résolution de problèmes algorithmiques'
metadescription:  "Programmation efficace - Les 128 algorithmes qu'il faut avoir compris et codés dans sa vie. Sortie le 1er mars 2016."
url:              http://tryalgo.org
baseurl:          "/"
images: 		  "/en/images/"

author:
  name:           'Jill-Jênn Vie'
  url:            https://twitter.com/jjvie

paginate:         5
paginate_path:    '/posts/page:num/'

# Custom vars
version:          2.1.0

github:
  tryalgo:        https://github.com/jilljenn/tryalgo
  meta:           https://github.com/jilljenn/tryalgo.org

# collections:
#   en:
#     output: true
#     permalink: /:collection/:title/
#   fr:
#     output: true
#     permalink: /:collection/:title/